BackendBundle\Entity\Claimcompany:
    type: entity
    table: claimcompany
    indexes:
        fk_claimcompany_company:
            columns:
                - company_id
        fk_claimcompany_user:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        lastname:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        position:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        businessemail:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        officenumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        personalnumber:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
    manyToOne:
        company:
            targetEntity: Company
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
