# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            
            form_login:
                login_path: /loginerror
                check_path: /login
            logout:
                invalidate_session: false
                path: /logout
                success_handler: logout_success_handler
                
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
