administrator_index:
    path: /administrar
    defaults: { _controller: AppBundle:Administrator:index }

administrator_company:
    path: /administrar/empresas
    defaults: { _controller: AppBundle:Administrator:companies}
    
administrator_comment:
    path: /administrar/comentarios
    defaults: { _controller: AppBundle:Administrator:comments}
    
administrator_user:
    path: /administrar/usuarios
    defaults: { _controller: AppBundle:Administrator:users}
    
administrator_allcompanies:
    path: /administrar/todas_empresas
    defaults: { _controller: AppBundle:Administrator:allCompanies}

administrator_delete_companies:
    path: /administrar/todas_empresas/eliminar={id}
    defaults: { _controller: AppBundle:Administrator:deleteCompanies }
    
administrator_delete_user:
    path: /administrar/usuarios/eliminar={id}
    defaults: { _controller: AppBundle:Administrator:deleteUsers }
    
administrator_validate_company:
    path: /administrar/empresas/validar={id}
    defaults: { _controller: AppBundle:Administrator:validateCompanies }

