administrator_index:
    path: /administrar
    defaults: { _controller: AppBundle:Administrator:index }

administrator_company:
    path: /administrar/empresas
    defaults: { _controller: AppBundle:Administrator:companies}
    
administrator_comment:
    path: /administrar/comentarios
    defaults: { _controller: AppBundle:Administrator:comments}
    
administrator_user:
    path: /administrar/usuarios
    defaults: { _controller: AppBundle:Administrator:users}
    
administrator_allcompanies:
    path: /administrar/todas_empresas
    defaults: { _controller: AppBundle:Administrator:allCompanies}
    

