administrator_index:
    path: /administrar
    defaults: { _controller: AppBundle:Administrator:index }

administrator_company:
    path: /administrar/{slug}
    defaults: { _controller: AppBundle:Administrator:companiesAdmin }
    
administrator_comment:
    path: /administrar/{slug}
    defaults: { _controller: AppBundle:Administrator:commentsAdmin }
