register-company:
    path: /register-company
    defaults: { _controller: AppBundle:Company:register }

companies_list:
    path: /companies
    defaults: { _controller: AppBundle:Company:companies }
    
companies_search:
    path: /search
    defaults: { _controller: AppBundle:Company:search }
    

    
companies_edit:
    path: /administrar/todas_empresas/editar
    defaults: { _controller: AppBundle:Company:edit }
    
    
# esta ruta debe pertenecer a otro yml
remove_opinion:
    path: /opinion/remove/{id}
    defaults: { _controller: AppBundle:Company:removeOpinion, id:null }
    
company_profile:
    path: /company/{id}
    defaults: { _controller: AppBundle:Company:profile, id:null }
    
rate:
    path: /rate/{id}
    defaults: { _controller: AppBundle:Rate:rate, id:null}
    

