home_companies:
    path: /home
    defaults: { _controller: AppBundle:Company:index }
    
companies_list:
    path: /companies
    defaults: { _controller: AppBundle:Company:companies }
    
companies_search:
    path: /search
    defaults: { _controller: AppBundle:Company:search }
    
# esta ruta debe pertenecer a otro yml
remove_opinion:
    path: /opinion/remove/{id}
    defaults: { _controller: AppBundle:Company:removeOpinion, id:null }
    

