register-company:
    path: /empresas/registrar
    defaults: { _controller: AppBundle:Company:register }

companies_list:
    path: /empresas
    defaults: { _controller: AppBundle:Company:companies }
    
companies_search:
    path: /busqueda
    defaults: { _controller: AppBundle:Company:search }
    

companies_edit:
    path: /administrar/todas_empresas/editar
    defaults: { _controller: AppBundle:Company:edit }

    
companies_points:
    path: /prueba
    defaults: { _controller: AppBundle:Company:puntos }
    
company_profile:
    path: /empresas/perfil
    defaults: { _controller: AppBundle:Company:profile }
    

    
    
    
# estas rutas deben pertenecer a otro yml
remove_opinion:
    path: /opinion/remove/{id}
    defaults: { _controller: AppBundle:Company:removeOpinion, id:null }
     
rate:
    path: /rate/{id}
    defaults: { _controller: AppBundle:Rate:rate, id:null}
    

