like_opinion:
    path: /like/{id}
    defaults: { _controller: AppBundle:Like:like, id:null}

unlike_opinion:
    path: /unlike/{id}
    defaults: { _controller: AppBundle:Like:unlike, id:null}
    
user_likes:
    path: /likes/{email}
    defaults: { _controller: AppBundle:Like:likes, email:null }
    
    
    