login:
    path: /login
    defaults: { _controller: AppBundle:User:login }

login_check:
    path: /login_check

logout:
    path: /logout

register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

user_email_test:
    path: /email-test
    defaults: { _controller: AppBundle:User:emailTest }
    methods: [POST]

user_edit:
    path: /my-data
    defaults: { _controller: AppBundle:User:editUser }

#esta ruta debe pertenecer a empresas, de momento se usara aqui para avanzar
companies_list:
    path: /companies
    defaults: { _controller: AppBundle:User:companies }
    
#esta ruta debe pertenecer a empresas, de momento se usara aqui para avanzar
companies_search:
    path: /search
    defaults: { _controller: AppBundle:User:search }