user_login:
    path: /login

user_logout:
    path: /logout
    
user_loginerror:
    path: /loginerror
    defaults: {_controller: AppBundle:User:loginerror}

user_register:
    path: /register
    defaults: { _controller: AppBundle:User:register }

user_email_test:
    path: /email-test
    defaults: { _controller: AppBundle:User:emailTest }
    methods: [POST]

user_edit:
    path: /cuenta/editar
    defaults: { _controller: AppBundle:User:editUser }

user_list:
    path: /people
    defaults: { _controller: AppBundle:User:user }