user_loginerror:
    path: /loginerror
    defaults: {_controller: AppBundle:User:loginerror}
    
user_login:
    path: /login

user_logout:
    path: /logout
    
user_register:
    path: /registrarse
    defaults: { _controller: AppBundle:User:register }

user_email_test:
    path: /email-test
    defaults: { _controller: AppBundle:User:emailTest }
    methods: [POST]
    
user_profile:
    path: /perfil
    defaults: { _controller: AppBundle:User:profile }
    
user_edit:
    path: /cuenta/editar
    defaults: { _controller: AppBundle:User:editUser }
    
user_change:
    path: /cuenta/cambiar/contraseña
    defaults: { _controller: AppBundle:User:viewChange }
    
user_change_password:
    path: /cuenta/cambiando/contraseña
    defaults: { _controller: AppBundle:User:changePassword }

user_list:
    path: /usuarios
    defaults: { _controller: AppBundle:User:user }

user_register_login:
    path: /cuenta/login
    defaults: { _controller: AppBundle:User:redirect }
    
user_forget:
    path: /recuperar/contraseña
    defaults: { _controller: AppBundle:User:viewForgetPassword }
    
user_forget_password:
    path: /recuperando
    defaults: { _controller: AppBundle:User:resetPassword }