BackendBundle\Entity\User:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacio"}
        plastname:
            - NotBlank: {message: "Los apellidos no pueden estar vacios"}
        email:
            - NotBlank: {message: "El email no puede estar vacio"}
            - Email:
                message: El email {{ value }} no es valido
                checkMX: false