BackendBundle\Entity\Estado:
    type: entity
    table: estados
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clave:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        abrev:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        activo:
            type: boolean
            nullable: false
            options:
                default: '1'
    lifecycleCallbacks: {  }
