BackendBundle\Entity\Opinion:
    type: entity
    table: opinions
    indexes:
        fk_opinion_company:
            columns:
                - company_id
        fk_opinion_user:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        generalcomment:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        point1:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point2:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point3:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point4:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point5:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point6:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point7:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point8:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point9:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        point10:
            type: string
            nullable: true
            length: 250
            options:
                fixed: false
        createdAt:
            type: datetime
            nullable: true
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            column: updated_at
    manyToOne:
        company:
            targetEntity: Company
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                company_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
