<?php

namespace Proxies\__CG__\BackendBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Company extends \BackendBundle\Entity\Company implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'tradename', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'rfc', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'logo', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'website', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businesssector', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'representant', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'contacname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'contactlastname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'position', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'telephoneext', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businessemail', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'personalnumber', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'status', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'document', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'createdAt', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'updatedAt', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'user', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businessname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'estado', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'municipio', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'localidad'];
        }

        return ['__isInitialized__', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'id', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'tradename', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'rfc', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'logo', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'website', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'description', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businesssector', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'representant', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'contacname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'contactlastname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'position', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'telephoneext', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businessemail', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'personalnumber', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'status', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'document', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'createdAt', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'updatedAt', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'user', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'businessname', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'estado', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'municipio', '' . "\0" . 'BackendBundle\\Entity\\Company' . "\0" . 'localidad'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Company $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTradename($tradename)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTradename', [$tradename]);

        return parent::setTradename($tradename);
    }

    /**
     * {@inheritDoc}
     */
    public function getTradename()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTradename', []);

        return parent::getTradename();
    }

    /**
     * {@inheritDoc}
     */
    public function setRfc($rfc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRfc', [$rfc]);

        return parent::setRfc($rfc);
    }

    /**
     * {@inheritDoc}
     */
    public function getRfc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRfc', []);

        return parent::getRfc();
    }

    /**
     * {@inheritDoc}
     */
    public function setLogo($logo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLogo', [$logo]);

        return parent::setLogo($logo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLogo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLogo', []);

        return parent::getLogo();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', [$website]);

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', []);

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinesssector($businesssector)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinesssector', [$businesssector]);

        return parent::setBusinesssector($businesssector);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinesssector()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinesssector', []);

        return parent::getBusinesssector();
    }

    /**
     * {@inheritDoc}
     */
    public function setRepresentant($representant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRepresentant', [$representant]);

        return parent::setRepresentant($representant);
    }

    /**
     * {@inheritDoc}
     */
    public function getRepresentant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRepresentant', []);

        return parent::getRepresentant();
    }

    /**
     * {@inheritDoc}
     */
    public function setContacname($contacname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContacname', [$contacname]);

        return parent::setContacname($contacname);
    }

    /**
     * {@inheritDoc}
     */
    public function getContacname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContacname', []);

        return parent::getContacname();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactlastname($contactlastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactlastname', [$contactlastname]);

        return parent::setContactlastname($contactlastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactlastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactlastname', []);

        return parent::getContactlastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosition($position)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosition', [$position]);

        return parent::setPosition($position);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosition()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosition', []);

        return parent::getPosition();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneext($telephoneext)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneext', [$telephoneext]);

        return parent::setTelephoneext($telephoneext);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneext()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneext', []);

        return parent::getTelephoneext();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessemail($businessemail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessemail', [$businessemail]);

        return parent::setBusinessemail($businessemail);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessemail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessemail', []);

        return parent::getBusinessemail();
    }

    /**
     * {@inheritDoc}
     */
    public function setPersonalnumber($personalnumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPersonalnumber', [$personalnumber]);

        return parent::setPersonalnumber($personalnumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getPersonalnumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPersonalnumber', []);

        return parent::getPersonalnumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocument($document)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocument', [$document]);

        return parent::setDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocument', []);

        return parent::getDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\BackendBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setBusinessname($businessname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBusinessname', [$businessname]);

        return parent::setBusinessname($businessname);
    }

    /**
     * {@inheritDoc}
     */
    public function getBusinessname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBusinessname', []);

        return parent::getBusinessname();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', [$estado]);

        return parent::setEstado($estado);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', []);

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipio($municipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipio', [$municipio]);

        return parent::setMunicipio($municipio);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipio', []);

        return parent::getMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocalidad($localidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocalidad', [$localidad]);

        return parent::setLocalidad($localidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocalidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocalidad', []);

        return parent::getLocalidad();
    }

}
